---

- name: Ensure fluentd is installed
  pkgng:
    name: rubygem-fluentd
    state: present

- name: Install missing gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - tzinfo-data

- name: Patch fluentd (issue \#30)
  patch:
    src: 0.12.14-ruby23.patch
    dest: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/plugin/filter_record_transformer.rb
    backup: yes
  notify: Restart fluentd

# this should be removed after 0.14.x released
- name: Install string-scrub
  gem:
    name: string-scrub
    version: 0.0.5
    state: present
    user_install: no
