---

- name: Install fluentd via gem
  gem:
    name: fluentd
    user_install: false
    state: present

- name: Get ruby version
  command: "ruby -e \"puts RUBY_VERSION.split('.')[0..1].join\"" # 19, 20, 21 ...
  register: register_fluentd_ruby_version_sym
  changed_when: false

- name: Get a list of gem binaries
  shell: "gem contents fluentd | grep -E '^/usr/local/lib/ruby/gems/[[:digit:]]+\\.[[:digit:]]+/gems/fluentd-[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+/bin/'"
  register: register_fluentd_gem_binary
  changed_when: false

- name: Create symlinks
  file:
    path: "/usr/local/bin/{{ item | basename }}"
    src: "/usr/local/bin/{{ item | basename }}{{ register_fluentd_ruby_version_sym.stdout }}"
    state: link
  with_items: "{{ register_fluentd_gem_binary.stdout_lines }}"

- name: Create _fluentd group
  group:
    name: _fluentd
    gid: 900

- name: Create _fluentd user
  user:
    name: _fluentd
    comment: Fluentd daemon
    shell: /sbin/nologin
    uid: 900
    group: _fluentd
    home: /var/empty
    createhome: false
    login_class: daemon
    state: present

- name: Copy rc.sub for fluentd
  copy:
    src: OpenBSD.rc.subr
    dest: /etc/rc.d/fluentd
    mode: 0755
  notify: Restart fluentd
