---
# handlers file for ansible-role-fluentd

- name: Restart fluentd
  service:
    name: "{{ fluentd_service_name }}"
    state: restarted

- name: Reload fluentd
  service:
    name: "{{ fluentd_service_name }}"
    state: reloaded
